### ISSUE TITLE
vzeroupper use without check cpu support

### ISSUE THREAD

**Issue by quamtum** [asmjit/cult#12]
Hi All
when i use cult in old cpu which not support vzeroupper like Q8200 (core2 cpu)
in master/src/asmjit/x86/x86emithelper.cpp line 538
 if (frame.hasAvxCleanup()) ASMJIT_PROPAGATE(emitter->vzeroupper());
or 
in master/src/cult/instbench.cpp line 1777
if (isVec(_instId, _instSpec))
    a.vzeroupper();
cult test all instruction (./cult)
near add r64,r64
maybe still use vzeroupper, so illegal instruction #UD occur and exit program

**Comment by kobalicek** [comment]
Thanks! Let me know if the issue has been fixed by that commit.

**Comment by quamtum** [comment]
Hi Petr Kobalicek
Thank you your support
It can work now.
________________________________
