### ISSUE TITLE
 #UD case2

### ISSUE THREAD

**Issue by quamtum** [asmjit/cult#13]
Hi All
When i build "cult" in AMD Ryzen 9 3900X 12-Core Processor
found src/cult/instbench.cpp will use
    a.kxnorq(x86::k7, x86::k7, x86::k7);
and       
    a.kmovw(pred, x86::k7);
but 3900x not support these instruction
maybe need add some check to avoid Illegal instruction (#UD)

**Comment by kobalicek** [comment]
I think this must be a bug in asmjit as CULT gets the CPU extensions support from its database, I will look into it.

**Comment by kobalicek** [comment]
Should be fixed by https://github.com/asmjit/asmjit/commit/0cd18daa5d530813fc4ece927391fdce726fa06a

You would have to update asmjit to master to verify.

**Comment by quamtum** [comment]
Hi [kobalicek](https://github.com/kobalicek)
Thanks your support, it can work now
